### ISSUE TITLE
Can you tell me the command to run the bot with config.yaml file 

### ISSUE THREAD

**Issue by premnathdey** [musse/event-scheduler-bot#1]

**Comment by musse** [comment]
@premnathdey you should first [build the bot with Go](https://www.digitalocean.com/community/tutorials/how-to-build-and-install-go-programs). Next, you create your `config.yaml` file based on [the steps on the readme](https://github.com/musse/event-scheduler-bot#how-to-use). Finally, you have to run the built binary from the same folder where your `config.yaml` file is. Assuming your binary is on the same folder of the `config.yaml` file, you can simply run `./event-scheduler-bot`.

**Comment by premnathdey** [comment]
Thanks
